import os
import logging
from sqlalchemy import desc # Imports SQLAlchemy's desc() function. Used to sort data in descending order.
from sqlalchemy.orm import Session
from app.models.report import Report
from app.models.uploaded_file import UploadedFile

logger = logging.getLogger("app")

# Contains all history and dashboard related business logic.
class HistoryService:
    @staticmethod
    def get_user_report_history(db: Session, user_id: int):
        """
        Retrieves list of all reports generated by a user.
        Includes file details by joining UploadedFile to resolve filenames.
        """
        logger.info(f"Retrieving report history list for user ID {user_id}.")
        query_result = db.query(Report, UploadedFile.filename).join(
            UploadedFile, Report.file_id == UploadedFile.id
        ).filter(
            Report.user_id == user_id
        ).order_by(
            desc(Report.created_at)
        ).all()
        
        history_list = []
        for report, filename in query_result:
            history_list.append({
                "id": report.id,
                "file_id": report.file_id,
                "filename": filename,
                "report_title": report.report_title,
                "summary": report.summary,
                "created_at": report.created_at
            })
            
        return history_list

    @staticmethod
    def get_dashboard_stats(db: Session, user_id: int) -> dict:
        """
        Calculates and aggregates dashboard statistics for the logged-in user.
        """
        logger.info(f"Aggregating dashboard statistics for user ID {user_id}.")
        
        # Count total files uploaded
        total_files = db.query(UploadedFile).filter(UploadedFile.user_id == user_id).count()
        
        # Count total reports generated
        total_reports = db.query(Report).filter(Report.user_id == user_id).count()
        
        # Fetch details of the latest generated report
        latest_report = db.query(Report).filter(
            Report.user_id == user_id
        ).order_by(
            desc(Report.created_at)
        ).first()
        
        latest_title = latest_report.report_title if latest_report else None
        latest_date = latest_report.created_at if latest_report else None
        
        # Calculate file extension/type counts
        uploaded_files = db.query(UploadedFile.filename).filter(UploadedFile.user_id == user_id).all()
        file_type_distribution = {}
        for (filename,) in uploaded_files:
            _, ext = os.path.splitext(filename.lower()) # Splits filename into : _ Stores the unused filename. ext Stores .csv , Example : sales.csv -> ("sales",".csv")
            ext_name = ext.lstrip('.') if ext else "unknown" # Removes the leading dot. Example : .csv -> csv
            file_type_distribution[ext_name] = file_type_distribution.get(ext_name, 0) + 1 # counting the files with particular extensions
            
        return {
            "total_files_uploaded": total_files,
            "total_reports_generated": total_reports,
            "latest_report_title": latest_title,
            "latest_report_date": latest_date,
            "file_type_distribution": file_type_distribution
        }