// pages/History.jsx
// Displays the complete history of all AI reports generated by the logged-in user.
//
// Fetches: GET /api/history → ReportListItem[]
// Each list item contains: { id, file_id, filename, report_title, summary, created_at }
//
// Features:
//   - Search bar to filter reports by title or filename
//   - Table with sortable date column (newest first by default)
//   - View button → navigates to /report/:id
//   - Download button → triggers HTML file download via backend
//   - Empty state message with link to Upload page

import { useEffect, useState, useMemo } from 'react'
import { Link } from 'react-router-dom'
import Layout  from '../components/Layout'
import Loader  from '../components/Loader'
import { getHistory, downloadReport } from '../services/report'
import { Search, ExternalLink, Download, FileText, AlertCircle, UploadCloud } from 'lucide-react'
import toast from 'react-hot-toast'

function formatDate(iso) {
  return new Date(iso).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })
}

export default function History() {
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)
  const [error,   setError]   = useState('')
  const [query,   setQuery]   = useState('')

  useEffect(() => {
    async function load() {
      setLoading(true)
      setError('')
      try {
        const data = await getHistory()
        setReports(data)
      } catch {
        setError('Failed to load report history. Please refresh.')
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [])

  // Filter by search query
  const filtered = useMemo(() => {
    if (!query.trim()) return reports
    const q = query.toLowerCase()
    return reports.filter(
      r => r.report_title.toLowerCase().includes(q) || r.filename.toLowerCase().includes(q)
    )
  }, [reports, query])

  async function handleDownload(id) {
    try {
      await downloadReport(id)
      toast.success('Report downloaded')
    } catch {
      toast.error('Download failed. Please try again.')
    }
  }

  return (
    <Layout>
      {/* ── Header row ───────────────────────────────────── */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          flexWrap: 'wrap',
          gap: 12,
          marginBottom: 24,
        }}
      >
        <div>
          <h1 className="page-title">Report History</h1>
          <p style={{ marginTop: 4, fontSize: '0.875rem', color: 'var(--text-muted)' }}>
            All AI reports you've generated in InsightAI.
          </p>
        </div>
        <Link to="/upload" className="btn-primary" style={{ textDecoration: 'none' }}>
          <UploadCloud size={16} />
          New Report
        </Link>
      </div>

      {loading ? (
        <div style={{ display: 'flex', justifyContent: 'center', paddingTop: 80 }}>
          <Loader size="lg" text="Loading history…" />
        </div>
      ) : error ? (
        <div className="alert alert-error">
          <AlertCircle size={16} style={{ flexShrink: 0 }} />
          <span>{error}</span>
        </div>
      ) : reports.length === 0 ? (
        /* Empty state */
        <div
          className="glass-card"
          style={{
            padding: '60px 24px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: 16,
            textAlign: 'center',
          }}
        >
          <div
            style={{
              width: 64,
              height: 64,
              borderRadius: 16,
              background: 'var(--primary-light)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <FileText size={32} color="var(--primary)" />
          </div>
          <div>
            <div style={{ fontWeight: 700, fontSize: '1.1rem', color: 'var(--text-primary)' }}>
              No reports yet
            </div>
            <div style={{ marginTop: 8, fontSize: '0.875rem', color: 'var(--text-muted)', maxWidth: 360 }}>
              Upload a dataset and generate your first AI report to see it here.
            </div>
          </div>
          <Link to="/upload" className="btn-primary" style={{ marginTop: 8, textDecoration: 'none' }}>
            <UploadCloud size={16} />
            Upload Dataset
          </Link>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          {/* ── Search bar ─────────────────────────────────── */}
          <div style={{ position: 'relative', maxWidth: 420 }}>
            <Search size={16} color="var(--text-muted)" style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none' }} />
            <input
              type="search"
              value={query}
              onChange={e => setQuery(e.target.value)}
              placeholder="Search by report title or filename…"
              className="input-field"
              style={{ paddingLeft: 38 }}
              id="history-search"
              aria-label="Search reports"
            />
          </div>

          {/* ── Results count ──────────────────────────────── */}
          <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
            Showing {filtered.length} of {reports.length} report{reports.length !== 1 ? 's' : ''}
          </div>

          {/* ── Table ─────────────────────────────────────── */}
          <div className="glass-card" style={{ padding: 0, overflow: 'hidden' }}>
            {filtered.length === 0 ? (
              <div style={{ padding: '40px 24px', textAlign: 'center', color: 'var(--text-muted)', fontSize: '0.875rem' }}>
                No reports match your search.
              </div>
            ) : (
              <div style={{ overflowX: 'auto' }}>
                <table className="data-table">
                  <thead>
                    <tr>
                      <th style={{ paddingLeft: 24 }}>#</th>
                      <th>Report Title</th>
                      <th>Source File</th>
                      <th>Generated On</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filtered.map((r, idx) => (
                      <tr key={r.id}>
                        <td style={{ paddingLeft: 24, color: 'var(--text-muted)', fontSize: '0.8rem', fontWeight: 600 }}>
                          {idx + 1}
                        </td>
                        <td>
                          <div style={{ fontWeight: 600, color: 'var(--text-primary)', fontSize: '0.875rem', maxWidth: 280 }}>
                            {r.report_title}
                          </div>
                          {r.summary && (
                            <div
                              style={{
                                marginTop: 2,
                                fontSize: '0.75rem',
                                color: 'var(--text-muted)',
                                display: '-webkit-box',
                                WebkitLineClamp: 1,
                                WebkitBoxOrient: 'vertical',
                                overflow: 'hidden',
                                maxWidth: 280,
                              }}
                            >
                              {r.summary}
                            </div>
                          )}
                        </td>
                        <td>
                          <span className="badge badge-primary">{r.filename}</span>
                        </td>
                        <td style={{ whiteSpace: 'nowrap', fontSize: '0.8rem' }}>
                          {formatDate(r.created_at)}
                        </td>
                        <td>
                          <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
                            <Link
                              to={`/report/${r.id}`}
                              title="View full report"
                              style={{
                                display: 'inline-flex', alignItems: 'center', gap: 4,
                                fontSize: '0.8rem', color: 'var(--primary)', fontWeight: 600, textDecoration: 'none',
                              }}
                            >
                              <ExternalLink size={13} /> View
                            </Link>
                            <button
                              onClick={() => handleDownload(r.id)}
                              title="Download as HTML"
                              style={{
                                display: 'inline-flex', alignItems: 'center', gap: 4,
                                fontSize: '0.8rem', color: 'var(--text-secondary)', fontWeight: 600,
                                background: 'transparent', border: 'none', cursor: 'pointer', fontFamily: 'inherit', padding: 0,
                              }}
                            >
                              <Download size={13} /> Download
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      )}
    </Layout>
  )
}