from fastapi import APIRouter, Depends, status
from sqlalchemy.orm import Session
from typing import List
from app.config.database import get_db
from app.schemas.report_schema import ReportListItem
from app.controllers.history_controller import HistoryController
from app.middlewares.auth import get_current_user
from app.models.user import User

# Creates a group of related API endpoints. Adds /history before every endpoint (/history). Groups these APIs under History in Swagger UI.
# Swagger UI is an automatically generated interactive webpage that documents all your FastAPI APIs. It lets you view, test, and understand your endpoints without using tools like Postman. Swagger UI: http://127.0.0.1:8000/docs — Interactive documentation where you can test APIs.
router = APIRouter(prefix="/history", tags=["History"])

@router.get("", response_model=List[ReportListItem], status_code=status.HTTP_200_OK)
def get_report_history(db: Session = Depends(get_db),current_user: User = Depends(get_current_user)):
    """
    Get a list of all historical reports generated by the current user.
    """
    return HistoryController.get_history(db, current_user.id)